services:
  - type: web
    name: video-processing-frontend
    env: node
    nodeVersion: 18
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm start
    rootDir: .
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: NEXTAUTH_URL
        value: "https://video-processing-frontend.onrender.com"
      - key: NEXTAUTH_SECRET
        sync: false
      - key: NEXT_PUBLIC_API_URL
        value: "https://video-processing-api.onrender.com"
      - key: R2_ENDPOINT
        sync: false
      - key: R2_ACCESS_KEY_ID
        sync: false
      - key: R2_SECRET_ACCESS_KEY
        sync: false
      - key: R2_BUCKET_NAME
        sync: false
    autoDeploy: true
    healthCheckPath: /api/healthcheck
